server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${fd.datasource.driver-class-name}
      url: jdbc:mysql://${fd.datasource.host}:${fd.datasource.port}/${fd.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${fd.datasource.username}
      password: ${fd.datasource.password}
  jpa:
    #这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB 用的
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #配置在日志中打印出执行的 SQL 语句信息。
    show-sql: true
    properties:
        hibernate:
      #配置指明在程序启动的时候要删除并且创建实体类对应的表
#          ddl-auto: create
          format_sql: true

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


  logging:
    level:
      # 基本类型绑定
      org.hibernate.type.descriptor.sql.BasicBinder: trace
      # 枚举类型绑定
      org.hibernate.metamodel.model.convert.internal.NamedEnumValueConverter: trace


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fd.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      fd:
        mapper: debug
        service: info
        controller: info

fd:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
